
name: Build PDF

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      # Runs a single command using the runners shell
      - name: Install tex-live
        run: |
          PROJECTDIR=$(pwd)
          cd /tmp && wget http://ftp.fau.de/ctan/systems/texlive/tlnet/install-tl-unx.tar.gz
          tar -xvzf install-tl-unx.tar.gz
          cd install-tl-*
          chmod +x install-tl
          sudo ./install-tl --profile=$PROJECTDIR/texlive.profile
          PATH=/usr/local/texlive/2017/bin/x86_64-linux:$PATH
          pdflatex -v
          cd $PROJECTDIR
          

      # Runs a set of commands using the runners shell
      - name: Build English
        run: pdflatex eng/main.tex -jobname=Resume-$(date +"%Y-+%m-%d")-eng

      - name: Build Italian
        run: pdflatex ita/main.tex -jobname=Resume-$(date +"%Y-+%m-%d")-ita

      - name: Add pdf files to git 
        run: git add *.pdf

      - name: Commit
        run: commit -m "Updated Resume PDFs"
      
      - name: Push
        run: git push origin master